### ISSUE TITLE
Remove signature selection dropdown

### ISSUE THREAD

**Issue by waldenraines** [unchained-capital/caravan#107]
## I'm submitting a…

* [ ] Regression (a behavior that used to work and stopped working in a new release)
* [ ] Bug report 
* [x] Feature request
* [ ] Documentation issue or request
* [ ] Support request

## Expected Behavior

Able to sign without selecting which key you are signing with.

## Current Behavior

Currently you can sign on the broadcast transaction page with any valid key but you first have to select which key you want to sign with.  Even if you select the other key it still accepts your signature so it seems like we should just remove the select.

In other words, given two signatures "a" and "b", if you select "b" on the broadcast page and sign with "a" then it still accepts the signature.  It knows that the signature is actually "a" and only gives me an option to select "b" for the other signature

![gscreenshot_2020-05-20-143413](https://user-images.githubusercontent.com/4116405/82483815-073ee600-9aa7-11ea-8431-434a70457567.png)

## Possible Solution

Remove the key selection dropdown for signatures.  We should just allow the user to select the type like they do on the address page:

![gscreenshot_2020-05-20-144216](https://user-images.githubusercontent.com/4116405/82484595-21c58f00-9aa8-11ea-9318-5f41a1f42ba7.png)

## Steps to Reproduce (for bugs)

1. Create a spend 
2. Go to signing page
3. Note that you have to select the key to sign

## Environment

N/A

**Comment by jevidon** [comment]
The Caravan Library is transitioning to a [new home](https://github.com/caravan-bitcoin/caravan), and as part of this move all current issues will be closed and archived. This specific request will be part of a larger refactor we plan to execute in the future.
