### ISSUE TITLE
Feature Request: Add Watch Only Address to bitcoind wallet

### ISSUE THREAD

**Issue by howech** [unchained-capital/caravan#12]
When operating in 'interact' mode, while using a private bitcoins node, one has to manually ensure that the multisig address one is spending from has been added to bitcoind's wallet. It would be super convenient if caravan had a mechanism to make the call to add the address in question from the interact page.

**Comment by jevidon** [comment]
This is now supported as a wallet feature in the new [Caravan repo](https://github.com/caravan-bitcoin/caravan).
