### ISSUE TITLE
Bug: ledger images missing in test runner signing tests

### ISSUE THREAD

**Issue by waldenraines** [unchained-capital/caravan#122]
## I'm submitting a…

* [ ] Regression (a behavior that used to work and stopped working in a new release)
* [x] Bug report 
* [ ] Feature request
* [ ] Documentation issue or request
* [ ] Support request

## Expected Behavior
Images should be shown.

## Current Behavior
Now images:

![gscreenshot_2020-04-29-203306](https://user-images.githubusercontent.com/4116405/82494081-0615b500-9ab7-11ea-88b7-116920cb8d70.png)

## Possible Solution
Show the images.

## Steps to Reproduce (for bugs)

1. Go to test runner
2. Set up ledger device with words
3. Go to test 25 or so
4. Start test
5. Note missing images

## Environment

* Where are you running caravan:  localhost
* Operating system: Linux
* Browser and version: Chrome

```
caravan@0.2.0 /home/walden/code/caravan
├── unchained-bitcoin@0.0.13 
└─┬ unchained-wallets@0.0.12 
  └── unchained-bitcoin@0.0.12 

npm: 6.14.4 
node: v12.16.2
Linux 5.6.13-arch1-1 #1 SMP PREEMPT Thu, 14 May 2020 06:52:53 +0000 x86_64 GNU/Linux
```

**Comment by waldenraines** [comment]
See also https://github.com/unchained-capital/caravan/issues/112 as a potential duplicate.

**Comment by bucko13** [comment]
Yeah, closing in favor of #112
