### ISSUE TITLE
Bug: caravan Test Suite detect version does not work for newer ledger firmwares

### ISSUE THREAD

**Issue by waldenraines** [unchained-capital/caravan#123]
## I'm submitting a…

* [ ] Regression (a behavior that used to work and stopped working in a new release)
* [x] Bug report 
* [ ] Feature request
* [ ] Documentation issue or request
* [ ] Support request

## Expected Behavior
Detect version should work for all hardware wallets.

## Current Behavior
I get an error when attempting to detect the version of most ledgers:

```
TransportError {name: "TransportError", message: "Failed to sign with Ledger device: U2F DEVICE_INELIGIBLE", stack: "Error↵    at new TransportError (https://localhost…calhost:3000/caravan/static/js/1.chunk.js:3359:13", id: "U2F_4", originalError: Error: Sign failed
    at makeError (https://localhost:3000/caravan/static/js/1.chunk.js:350560:15)…}
```

I tried with the following wallets:
- Ledger Nano S v1.5.5 (MCU v1.7)
- Ledger Nano S v1.6.0 (MCU v1.11)
- Ledger Nano X v1.2.4-1 (MCU 2.8)

The only one that worked was:
- Ledger Nano S v1.5.5 (MCU v1.7)

![gscreenshot_2020-04-29-204055](https://user-images.githubusercontent.com/4116405/82495045-85f04f00-9ab8-11ea-9397-d18bf4d7d79f.png)

## Possible Solution

Fix the above.

## Steps to Reproduce (for bugs)

1. Go to test suite
2. Attempt to detect version of ledger
3. Note error 

## Environment

* Where are you running caravan:  localhost
* Operating system: Linux
* Browser and version: Chrome

```
caravan@0.2.0 /home/walden/code/caravan
├── unchained-bitcoin@0.0.13 
└─┬ unchained-wallets@0.0.12 
  └── unchained-bitcoin@0.0.12 

npm: 6.14.4 
node: v12.16.2
Linux 5.6.13-arch1-1 #1 SMP PREEMPT Thu, 14 May 2020 06:52:53 +0000 x86_64 GNU/Linux
```

**Comment by humanumbrella** [comment]
Interestingly, I just tested this one and it worked for me. Hmm.
![Screen Shot 2020-12-09 at 10 42 51 PM](https://user-images.githubusercontent.com/10471648/101731314-50b94780-3a70-11eb-8111-bce79e43c84c.png)

**Comment by waldenraines** [comment]
I think this may be invalid, it also works for me now that we're using webusb.
