### ISSUE TITLE
Bug: entering in bip32 path is tedious

### ISSUE THREAD

**Issue by waldenraines** [unchained-capital/caravan#126]
## I'm submitting a…

* [x] Regression (a behavior that used to work and stopped working in a new release)
* [x] Bug report 
* [ ] Feature request
* [ ] Documentation issue or request
* [ ] Support request

## Expected Behavior

The validation should not kick you out to the end of the input field while inputting a bip32 path.

## Current Behavior
The cursor moves to end of the line as I edit my bip32 path, see the gif:

![Peek 2020-05-18 15-46](https://user-images.githubusercontent.com/4116405/82495837-bdabc680-9ab9-11ea-83e6-5e42e40d3ad0.gif)

## Possible Solution
Implement validation that does not affect the cursor.

## Steps to Reproduce (for bugs)

1. Get to any of the inputs for bip32 path
2. Attempt to change one of the midsections of the path
3. Note that the cursor jumps to the end

## Environment

* Where are you running caravan:  localhost
* Operating system: Linux
* Browser and version: Chrome

```
caravan@0.2.0 /home/walden/code/caravan
├── unchained-bitcoin@0.0.13 
└─┬ unchained-wallets@0.0.12 
  └── unchained-bitcoin@0.0.12 

npm: 6.14.4 
node: v12.16.2
Linux 5.6.13-arch1-1 #1 SMP PREEMPT Thu, 14 May 2020 06:52:53 +0000 x86_64 GNU/Linux
```

**Comment by waldenraines** [comment]
This still happens on the script explorer page and the address creation page.

**Comment by waldenraines** [comment]
This has now been fixed on the address page but is still broken on the script explorer page.

**Comment by jevidon** [comment]
The Caravan Library is transitioning to a new home, and as part of this move current issues will be closed and archived. This issue has been closed as part of the migration - please go check out the new location here: https://github.com/caravan-bitcoin/caravan/issues
