### ISSUE TITLE
Bug: cannot sign a bech32 transaction with hermit in caravan

### ISSUE THREAD

**Issue by waldenraines** [unchained-capital/caravan#128]
## I'm submitting a…

* [ ] Regression (a behavior that used to work and stopped working in a new release)
* [x] Bug report 
* [ ] Feature request
* [ ] Documentation issue or request
* [ ] Support request

## Expected Behavior

Able to sign a bech32 transaction with hermit in caravan.

## Current Behavior

I get the following error when attempting to do so:
```
Unsupported output address type. bech32 addresses are unsupported.
```

This is likely just a bug with [unchained-wallets](https://github.com/unchained-capital/unchained-wallets) see https://github.com/unchained-capital/unchained-wallets/issues/20

## Possible Solution

Upgrade `unchained-wallets` after this has been fixed there.

## Steps to Reproduce (for bugs)

1. Create a p2sh wallet or address using hermit as one of the signers
2. Create a bech32 spend
3. Attempt to sign with hermit
4. Note above message 

## Environment

* Where are you running caravan:  localhost
* Operating system: Linux
* Browser and version: Chrome

```
caravan@0.2.0 /home/walden/code/caravan
├── unchained-bitcoin@0.0.13 
└─┬ unchained-wallets@0.0.12 
  └── unchained-bitcoin@0.0.12 

npm: 6.14.4 
node: v12.16.2
Linux 5.6.13-arch1-1 #1 SMP PREEMPT Thu, 14 May 2020 06:52:53 +0000 x86_64 GNU/Linux
```

**Comment by jevidon** [comment]
Closing this issue for now, however there will be some overall improvements to Hermit functions within Caravan.
