### ISSUE TITLE
Bug: no warning that you are unable to sign p2wsh with hermit when creating a new address/wallet

### ISSUE THREAD

**Issue by waldenraines** [unchained-capital/caravan#129]
## I'm submitting a…

* [ ] Regression (a behavior that used to work and stopped working in a new release)
* [x] Bug report 
* [ ] Feature request
* [ ] Documentation issue or request
* [ ] Support request

## Expected Behavior

We should show a warning when attempting to create a p2wsh address or wallet with hermit as one of the signers or prevent the user from doing so as they cannot sign with hermit.

## Current Behavior

You are not prevented from creating an address or wallet.  When you go to sign a transaction the signature UI simply isn't shown, there are no error messages:

![gscreenshot_2020-05-12-114432](https://user-images.githubusercontent.com/4116405/82496706-2778a000-9abb-11ea-87cf-6320f6ef2edc.png)
![gscreenshot_2020-05-12-114610](https://user-images.githubusercontent.com/4116405/82496707-2778a000-9abb-11ea-82b6-ee0b7d7190c8.png)

## Possible Solution

Show a message or prevent the user from creating a p2wsh address or wallet with hermit.

## Steps to Reproduce (for bugs)

1. Create a P2WSH address or wallet with hermit as one of the quorum
2. Attempt to spend
3. Note that the UI isn't shown and there is no message about why you can’t sign

## Environment

* Where are you running caravan:  localhost
* Operating system: Linux
* Browser and version: Chrome

```
caravan@0.2.0 /home/walden/code/caravan
├── unchained-bitcoin@0.0.13 
└─┬ unchained-wallets@0.0.12 
  └── unchained-bitcoin@0.0.12 

npm: 6.14.4 
node: v12.16.2
Linux 5.6.13-arch1-1 #1 SMP PREEMPT Thu, 14 May 2020 06:52:53 +0000 x86_64 GNU/Linux
```

**Comment by jevidon** [comment]
Closing this issue for now, however there will be some overall improvements to Hermit functions within Caravan.
