### ISSUE TITLE
Remove `method` and `client` fields from wallet config.

### ISSUE THREAD

**Issue by destrys** [unchained-capital/caravan#139]
The method and clients fields in the config are unnecessary, and aren't fixed over time.
A user can change devices, no reason to lock them into a specific device.
And a user may want to switch between public and private nodes.

* [ ] Regression (a behavior that used to work and stopped working in a new release)
* [ ] Bug report 
* [x] Feature request
* [ ] Documentation issue or request
* [ ] Support request

**Comment by bucko13** [comment]
Related to #130

**Comment by waldenraines** [comment]
Note that in order to fix this we'll also have to add the ability to alter the node before loading the wallet.

**Comment by bucko13** [comment]
My suggestion for how to approach this is to not require the client in the config, but when one is loaded without a config, the confirmation page will have the Client Picker as a way for this information to be set. This keeps support for the client type in the config, but makes it optional.

Alternatively, the Client Picker could always be displayed in the confirmation page when a config is loaded, pre-set if it's present in the config but free to be altered. To "save" this information, a new config can be downloaded after making changes. This probably requires the least amount of changes. 

The device type (i.e. `method`), as per #130 should be removed from the config however with required adjustments made to the signing and address verification flow.

**Comment by jevidon** [comment]
The Caravan Library is transitioning to a [new home](https://github.com/caravan-bitcoin/caravan), and as part of this move all current issues will be closed and archived. This request has been resolved and will not be migrated over.
