### ISSUE TITLE
Provide a multiarch docker container

### ISSUE THREAD

**Issue by Kukks** [unchained-capital/caravan#141]
## I'm submitting a…

* [ ] Regression (a behavior that used to work and stopped working in a new release)
* [ ] Bug report 
* [x] Feature request
* [ ] Documentation issue or request
* [ ] Support request

## Expected Behavior

Create a multi-arch (amd64, arm32, arm64) docker image, published to Docker Hub, on each new tagged version.

## Current Behavior

Have to manually build a docker container and users need to trust me instead of the official devs. Risks of becoming outdated easily

## Possible Solution

The work for this should be more or less identical to https://github.com/Ride-The-Lightning/c-lightning-REST/blob/master/.circleci/config.yml

**Comment by bucko13** [comment]
Very old issue, sorry for not getting to this sooner, but as we've worked on consolidating and cleaning up our open source code, moving over to a new monorepo, revisiting images and automation has come up as something we want to address.

Here's our new image file: https://github.com/caravan-bitcoin/caravan/blob/main/apps/coordinator/Dockerfile

Working out the kinks of the automation: https://github.com/caravan-bitcoin/caravan/actions/workflows/dockerhub.yml

Thanks again!
