### ISSUE TITLE
Allow for a start block value when doing a node rescan.

### ISSUE THREAD

**Issue by destrys** [unchained-capital/caravan#143]
## I'm submitting a…

* [ ] Regression (a behavior that used to work and stopped working in a new release)
* [ ] Bug report 
* [x] Feature request
* [ ] Documentation issue or request
* [ ] Support request

## Expected Behavior

A user should be able to reduce the time of a rescan if they know that their wallet has no transaction below a certain block number.

## Current Behavior

There is no option to limit the rescan, it starts from block zero, meaning a rescan can take hours.
Ref: https://twitter.com/dlawnroac/status/1269232935170957312

## Possible Solution

If it's not possible with `importmulti` we may need to use `rescanblockchain`which does have a `start_height` parameter.

**Comment by jevidon** [comment]
This issue has been migrated to the new caravan monorepo: https://github.com/caravan-bitcoin/caravan/issues/68
