### ISSUE TITLE
Node connection does not work with UC hosted Caravan, but works with MyNode hosted Caravan

### ISSUE THREAD

**Issue by sahilc0** [unchained-capital/caravan#144]
## I'm submitting a…

* [ ] Regression (a behavior that used to work and stopped working in a new release)
* [x ] Bug report 
* [ ] Feature request
* [ ] Documentation issue or request
* [ ] Support request

## Expected Behavior
Put in node URL, user and pass, and get confirmed connection when using https://unchained-capital.github.io/caravan/#/wallet

## Current Behavior
When using Github/UC hosted Caravan (https://unchained-capital.github.io/caravan/#/wallet), putting in node information leads to error. 

However when putting in the **same** node information on MyNode (raspi node in a box) hosted Caravan, connection is successful.
**Github hosted:**
![image](https://user-images.githubusercontent.com/8256062/85212649-b9b5d300-b309-11ea-9a38-2acfef69c6a5.png)
**MyNode local**
![image](https://user-images.githubusercontent.com/8256062/85212651-be7a8700-b309-11ea-89a9-fcdb494288c4.png)

MyNode instructions: 
![image](https://user-images.githubusercontent.com/8256062/85212658-c76b5880-b309-11ea-8858-467c4a724c8c.png)

* Where are you running caravan:  UC/GitHub VS MyNode local
* Operating system: macOS
* Browser and version: Brave

**Comment by waldenraines** [comment]
Thanks for the issue report!

I have a couple of questions if you don't mind.  

- Is your node publicly accessible?  If the URL is like the one above (i.e. an internal network IP like `192.168.1.101` or `mynode.local`) then it won't be accessible via github pages.
- If so, are you running a CORS proxy?  See https://github.com/unchained-capital/caravan#adding-cors-headers

**Comment by sahilc0** [comment]
Hey thanks @waldenraines - you are correct, I just realized it is not publicly accessible. 
What can I do in this case? My guess is I have the following options - can you advise?
1. Make my node publicly accessible to get the required info for Caravan
2. Use the Caravan built into MyNode

**Comment by sahilc0** [comment]
What if you could connect to MyNode over Tor?

**Comment by sahilc0** [comment]
OK - according to MyNode: "There is not a way to connect to the bitcoind RPC port publicly for security reasons."

**Comment by waldenraines** [comment]
> * Make my node publicly accessible to get the required info for Caravan

Definitely wouldn't recommend this approach.  

> * Use the Caravan built into MyNode

Apparently there is an issue with that https://github.com/mynodebtc/mynode/issues/338.  

You could also probably run caravan on the same local network your MyNode is on and connect that way (i.e. `192.168.1.n`).  I haven't tested this out with MyNode specifically but it should work provided you know the RPC username and password.  Make sure you refer to the section about cors headers mentioned above though.
