### ISSUE TITLE
Feature: Starting Address Index

### ISSUE THREAD

**Issue by destrys** [unchained-capital/caravan#149]
When loading a wallet, a user may not have started at bip32 suffix `0/0`, but at a higher index, `0/X`. 
Caravan should allow at user to set the 'Starting Address Index', and read this parameter from a wallet config file.

The default value for the Starting Address Index should be zero.

Even if a user specifies a starting address index, or loads it in a wallet config file, we should allow the user to see previous, unused addresses if they wish. But it's probably better to hide them by default. Maybe this could be included in 'show zero balance addresses' selector. 
On second though, that may not work because those addresses may not have been scanned for transactions already (imagine the starting address is 1000, do we want to always scan those first 1000 addresses? probably not.)
So changing the Starting Address Index should suggest to the user to do a rescan.

* [ ] Regression (a behavior that used to work and stopped working in a new release)
* [ ] Bug report 
* [x] Feature request
* [ ] Documentation issue or request
* [ ] Support request

**Comment by waldenraines** [comment]
This was fixed via https://github.com/unchained-capital/caravan/pull/154
