### ISSUE TITLE
How to change client type in the config file?

### ISSUE THREAD

**Issue by sahilc0** [unchained-capital/caravan#150]
## I'm submitting a…

* [ ] Regression (a behavior that used to work and stopped working in a new release)
* [ ] Bug report 
* [ ] Feature request
* [ ] Documentation issue or request
* [x ] Support request

Is it possible to change the client type (public to private) on the config file after the fact?
![image](https://user-images.githubusercontent.com/8256062/86059519-c5934a80-ba17-11ea-9d77-bf84be1f432e.png)

For example: initially created wallet with client type = public. Later, want to connect to node so want to change client type to private. What other parameters do I need to add to the file to change this?

**Comment by bucko13** [comment]
Hey @sahilc0, 

We actually just published an update by @destrys that adds support for a config that doesn't have any client specified ([here](https://github.com/unchained-capital/caravan/blob/master/CHANGELOG.md#021-2020-06-29)). When you upload the config, the confirmation page will then just ask you which client type you'd like to use to connect with. You can try this out by just deleting the client field from the json. As long as the rest of the json is valid, it should all work! 

Let us know if that works for you. Feel free to re-open if not.

**Comment by waldenraines** [comment]
> Is it possible to change the client type (public to private) on the config file after the fact?

Caravan is stateless, you can change anything you want in the file and caravan will faithfully interpret it as such.  

Of course if you go and change your quorum, address type, network, BIP32 paths or xpubs then the generated wallet will not have the same addresses (and thus not have the same UTXOs/balance).

But feel free to change your client, the name of your wallet, your xpub names, or the methods (you can actually even remove the method entirely and it will give you a method dropdown selector when signing).  The latter change is useful in case you have to restore a wallet on another type of device from your BIP39 wallet words.
