### ISSUE TITLE
Path for coldcard

### ISSUE THREAD

**Issue by sahilc0** [unchained-capital/caravan#152]
## I'm submitting a…

* [ ] Regression (a behavior that used to work and stopped working in a new release)
* [ ] Bug report 
* [ ] Feature request
* [ ] Documentation issue or request
* [x ] Support request

What  bip32 path is recommended when pasting an XPUB from coldcard? (Until it's officially supported)
![image](https://user-images.githubusercontent.com/8256062/86209775-24e08000-bb28-11ea-9d70-cba394dde5bf.png)

**Comment by sahilc0** [comment]
Tried this - but get an error:
![image](https://user-images.githubusercontent.com/8256062/86272200-09ef2980-bb83-11ea-9851-42ee992b3710.png)

**Comment by bucko13** [comment]
At the wallet or address creation stage, you don't need the BIP32 path, you just need to know the path that the xpub was generated from. Caravan doesn't need to know it though, just the xpub that it will derive addresses from. `Derive From extended public key` (which is what it looks like you're using) should probably be removed from the wallet page I'm thinking since that's not really applicable for the wallet, only single address creation.

**Comment by sahilc0** [comment]
Thanks @bucko13  - in that case would you recommend just doing "enter as text" for coldcard (until natively integrated)? And then leave bip32 path as default?

**Comment by sahilc0** [comment]
Pasting xpub "Enter as text" - I get this info/warning: 
![image](https://user-images.githubusercontent.com/8256062/86302536-e4334600-bbbd-11ea-9862-7d0a63aca489.png)
Does that just mean to keep note of the wallet (in my case coldcard) path, shown in the [walletsrecovery.org screenshot in OP?](https://github.com/unchained-capital/caravan/issues/152#issue-648706466)

**Comment by waldenraines** [comment]
> `Derive From extended public key` (which is what it looks like you're using) should probably be removed from the wallet page I'm thinking since that's not really applicable for the wallet, only single address creation.

I brought this up to @dhruvbansal and I'll quote his response below (hope you don't mind :smirk:):

> I’d like to keep this functionality.  It has nothing to do with the single-address-at-a-time flow.  It’s useful when trying to understand how related xpubs derive from one another...Being able to enter an xpub based off another makes it really easy to see how these different xpubs are related in caravan.

That said I think we could stand to have some informational text about the intended usage of this functionality.

**Comment by waldenraines** [comment]
> Does that just mean to keep note of the wallet (in my case coldcard) path, shown in the [walletsrecovery.org screenshot in OP?](https://github.com/unchained-capital/caravan/issues/152#issue-648706466)

Yeah, that is to say: make sure you know the BIP32 path for this particular xpub so you can derive it again with a different wallet, if needed.

**Comment by jevidon** [comment]
The Caravan Library is transitioning to a [new home](https://github.com/caravan-bitcoin/caravan), and as part of this move current issues will be closed and archived. If you're still interested in your feature request being addressed, you're welcome to reopen it at the new location: [https://github.com/caravan-bitcoin/caravan/issues](https://github.com/caravan-bitcoin/caravan/issues)
