### ISSUE TITLE
Bech32 2/3 MultiSig with WIF private keys: Signature for input 1 is invalid

### ISSUE THREAD

**Issue by ViktorBohu** [unchained-capital/caravan#156]
I'm submitting a Bug Report / Documentation /Support request. (unsure if it's an error or I am doing sth wrong)

This issue is referring to #19, #20 & #28 but in none of them a working solution was supplied.

## Steps to Reproduce

1. Create 3 public/private key pairs with bitadress.org and make a 2/3 Bech32 (P2WSH) mainnet adress with caravan:
bc1q8739hg8zrq89yhdlz8t4y2jz3u6axr3rf3slnfnt8jzee5zdel0q3k3rt3

2. Add some balance (I added 0.002 BTC)

3. Try to spend from it. Witness Script:
524104081503be35b900bef2d2db6fb65cf3f5e07623819ac6161ed6e7695a3d39dfcc446ce1cab7964b89158881464f49ca3e72e6d4ca39974fbeae9d28b44afc1c3e41046a6f70ada4c917053a98236d5905f3d29a0b5d50c835da4750f47a5d7c96d73ad8cadf62c1408545bd2394e29bf3224e61c8ad92eb29bcc0bcd44bcda5be884d4104c1fa73d6da997069b0b97ee228b9995743dd44a88cc94d8ce758e7af021717940c08e7b64d17aad40d74bd8a1a169ae0abf4b724a9edb71af8b25b8a209feaa553ae

4. Unsigned TX:
0100000001c417a7cb36e7093fc69269a4a828a0de88152e376029f66541110bcea2a595f30000000000ffffffff01630b03000000000017a914ae4335f9ecd3ef9257c92cad649e9124e62606288700000000

5.1. Sign the TX with coinb.in with one of the private keys (in WIF):
0100000001c417a7cb36e7093fc69269a4a828a0de88152e376029f66541110bcea2a595f3000000006b483045022100e29fae68d734b6458ff9300f5a12bac709a52af40a8dad160873fddba49a45d902200aa87e43c84e4a98fdcdb1de9e387367c77f08338a87cd6b0a89600a791cf2490121036a6f70ada4c917053a98236d5905f3d29a0b5d50c835da4750f47a5d7c96d73affffffff01630b03000000000017a914ae4335f9ecd3ef9257c92cad649e9124e62606288700000000

5.2. Inspect the signed TX here: https://rsbondi.github.io/btc-adventure/
ScriptSig in ASM:
3045022100e29fae68d734b6458ff9300f5a12bac709a52af40a8dad160873fddba49a45d902200aa87e43c84e4a98fdcdb1de9e387367c77f08338a87cd6b0a89600a791cf24901

6. Paste ether the full signed TX or only the ScriptSig (ASM) into caravan (in a JSON array ["..."]).
This throws the error "Signature for input 1 is invalid."

What am I missing/doing wrong?

## Possible Solution

I tried pasting the ScriptSig in HEX not ASM, not working.
I tried all 3 keys for signing. None were working. 100% sure I have the right keys.
Coinb.in doesn't allow signing the TX multiple times with different private keys for some reason.
Electrum only allows signing with a seed phrase.
Maybe signing in Bitcoin Core / bitcoin-cli works. I got the error "Input not found or already spent" with _signrawtransactionwithkey_ but haven't downloaded the whole blockchain yet so I'll try that again tomorrow.

## Environment
Running caravan (v0.2.1) on unchained-capital.github.io on an iMac (macOS 10.15.5) in Chrome (83.0.4103.116)

**Comment by ViktorBohu** [comment]
This is the first private key: L55Nv6Fy4PhoH71vRov3oPgJR2THMZz6XGXDbiKUeCUGVzFXUHby

How can a valid signature be generated from it?

**Comment by waldenraines** [comment]
Hey @ViktorBohu thanks for the issue.

We can only support use cases where keys and addresses are generated using caravan.

> How can a valid signature be generated from it?

You can use the bitcoin cli to generate the signature from a private key.

There is no known issue in caravan for adding valid individual signatures via text.  The text signature should be formatted like this:

```
["30440220305dc9bce028cd6856b14b7670b622cad1300c8f7e6d8522094ddb988b6edbad022032fc55a62c7b817ce375c379fb8a82be978a7edb13b0a375cdb7fea26238507e01","3045022100ecf20f7092036e55c2887f8cb15285edbcdc16e07977586e0f24b7dcf3973a9c022009adc8168c9d0791a19a966590958a54b8d4a440304d9b8b160993932ea2e4f501","304402201ba7ce0b19d8bd076103d0f087872ff5106d27a5b16a8cc14e45b12576d7657d022005044c3a0a90e00c2d116a8197875715081da56f67a2e8f63b1a7c3edc6ac2f901","30440220156bc557dae513ec7a4c752c788d5585569922d029879d2a397c68d9150ed1e0022032ee3bb1fa057e75f8c57e4b0681e524b84c3ac3bc59f71a4468c9826427bc8601","3044022070d658b82421ae2542d64fd7bda2dffb50a6c43b2d4a4d59bee684c6c413b2ea02207c8c4dc2c80f374341d6c47c04ecfcd583658d8038f39b74c6f2a386aefe508701"]
```
