### ISSUE TITLE
RBF

### ISSUE THREAD

**Issue by sahilc0** [unchained-capital/caravan#169]
## I'm submitting a…

* [ ] Regression (a behavior that used to work and stopped working in a new release)
* [ ] Bug report 
* [x] Feature request
* [ ] Documentation issue or request
* [x] Support request

I'm not sure if I'm phrasing this correctly - but can I signal RBF when spending a UTXO with caravan? User need being: if txn fees rise during bull market, user may want to bump up fee to make sure txn not stuck in mempool for too long.

**Comment by bucko13** [comment]
It's not currently supported but I think it would be a great feature to have, especially given how multisig can be more sensitive to fee rates.

**Comment by jevidon** [comment]
Migrated to the new monorepo: https://github.com/caravan-bitcoin/caravan/issues/69
