### ISSUE TITLE
Option to have native descriptor wallets

### ISSUE THREAD

**Issue by Bosch-0** [unchained-capital/caravan#177]
## I'm submitting a…

* [ ] Regression (a behavior that used to work and stopped working in a new release)
* [ ] Bug report 
* [X] Feature request
* [ ] Documentation issue or request
* [ ] Support request

## Expected Behavior

Option to have native descriptor wallets instead of current xpub / derivation path format. No wallets are currently using descriptors AFAIK it would be good to see caravan as one of the first to use this feature. It would make wallet backs more failproof / lead to a overall better UX. 

These could be used as an optional feature at first but eventually these types of wallets should be pushed for as the standard for wallet backups. 

https://github.com/bitcoin/bitcoin/pull/16528
[Video explaining Native Descriptor Wallets ](https://www.youtube.com/watch?v=xC25NzIjzog)

**Comment by jevidon** [comment]
This is now supported in the [new Caravan library](https://github.com/caravan-bitcoin/caravan)!
