### ISSUE TITLE
Ledger nano S import doesnt work

### ISSUE THREAD

**Issue by starsoccer** [unchained-capital/caravan#182]
## I'm submitting a…

* [ ] Regression (a behavior that used to work and stopped working in a new release)
* [X] Bug report 
* [ ] Feature request
* [ ] Documentation issue or request
* [ ] Support request

## Expected Behavior

Extended Public key to be imported

## Current Behavior

When clicking import extended public key error appears saying unable to reset the device

## Steps to Reproduce (for bugs)

1. Open caravaan app and click wallet
2. select for extended public key 1 ledger device
3. Connect ledger nano S
4. Unlock ledger nano S and start bitcoin app
5. Click Import extended public key

## Environment

* Where are you running caravan:  unchained-capital.github.io
* Operating system: Windows
* Browser and version: Chrome 87

**Comment by waldenraines** [comment]
Chrome v87+ enables a "new usb backend" by default:

```We are rolling out enabling chrome://flags#new-usb-backend by default in M-87```
 from [this chromium dev link](https://bugs.chromium.org/p/chromium/issues/detail?id=1150758#c1). 

This doesn't work well with Ledger.  A workaround:

Disable the new-usb-backend and use the old version:

1. Paste this in the Chrome URL bar: chrome://flags#new-usb-backend
2. Change it to be Disabled if it shows up as Default enabled.
3. Chrome will refresh

**Comment by starsoccer** [comment]
Confirmed it works, it would be good if caravan had a warning or notice to warn users if the ledger import fails and the user agent is greater then chrome 87

**Comment by waldenraines** [comment]
> Confirmed it works, it would be good if caravan had a warning or notice to warn users if the ledger import fails and the user agent is greater then chrome 87

See https://github.com/unchained-capital/caravan/issues/187
