### ISSUE TITLE
Intermittent JS error when broadcasting transactions

### ISSUE THREAD

**Issue by waldenraines** [unchained-capital/caravan#184]
## I'm submitting a…

* [ ] Regression (a behavior that used to work and stopped working in a new release)
* [x] Bug report 
* [ ] Feature request
* [ ] Documentation issue or request
* [ ] Support request

## Expected Behavior

No JS error

## Current Behavior

I get a JS errors when broadcasting some transactions.  There is also a 404 to `/api/tx/:txid/hex` from attempting to get the TX from blockstream:

```
Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
    at _callee2$ (walletActions.js:172)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:274)
    at Generator.prototype.<computed> [as next] (runtime.js:97)
    at asyncGeneratorStep (asyncToGenerator.js:3)
    at _next (asyncToGenerator.js:25)
```

It seems like this happens when the transaction hex isn't quite available on blockstream at the time the async call is made.

## Possible Solution

Perhaps timeout and retry?

## Steps to Reproduce (for bugs)

1. Construct a spend and sign it
2. Click broadcast
3. Note error (sometimes)

## Environment

* Where are you running caravan:  localhost
* Operating system: Linux
* Browser and version: Chromium

```
[walden:~/code/caravan] 4c07fe4+ ± npm ls caravan unchained-bitcoin unchained-wallets; echo -e npm: `npm -v` \\nnode: `node -v`;  uname -a | xargs echo | cut -d " " -f 1,3-15 || sw_vers
caravan@0.3.3 /home/walden/code/caravan
├── unchained-bitcoin@0.1.0 
└─┬ unchained-wallets@0.1.13 
  └── unchained-bitcoin@0.1.0  deduped

npm: 6.14.4 
node: v12.16.2
Linux 5.9.9-arch1-1 #1 SMP PREEMPT Wed, 18 Nov 2020 19:52:04 +0000 x86_64 GNU/Linux
```

**Comment by jevidon** [comment]
Resolved.
