### ISSUE TITLE
Invalid Channel Error - Unable to Maintain Connection to Bitcoin App during Import Process

### ISSUE THREAD

**Issue by JeremyNau** [unchained-capital/caravan#186]
## I'm submitting a…

* [ ] Regression (a behavior that used to work and stopped working in a new release)
* [ ] Bug report 
* [ ] Feature request
* [ ] Documentation issue or request
* [x] Support request

## Expected Behavior

When creating a multi-sig wallet, and using a Ledger Nano X device, I should be able to import my xPub after I log into my device, access the Bitcoin App, and press the "Import Extended Key" button.

## Current Behavior

I am unable to import my Xpub from my Ledger. As soon as I press the Import Public Key Button, I am prompted to connect to my device. Upon doing so, I am automatically disconnected from the bitcoin app on my Ledger and my key is not imported.

It seems doesn't occur 100% of the time for some reason, but has happened about 2/3 of the time for me.

It also seems to only occur when I am trying to create a Wallet. I have no issues when creating an address.

![image](https://user-images.githubusercontent.com/55710632/102019397-3b6e4280-3d28-11eb-94a4-95265c821574.png)

## Steps to Reproduce (for bugs)

- I am creating a 2-of-3 MultiSig Wallet.
- To import an extended key, I am using a Ledger Nano X (but the same is happening with my S)
- I unlock my Ledger and access my bitcoin app
- I press the "Import Extended Public Key" button.
- I locate my device, and press the "Connect" button.

![image](https://user-images.githubusercontent.com/55710632/102019082-1f69a180-3d26-11eb-99d3-91173ebd81b0.png)

- As soon as I press the connect button, I am logged out of the bitcoin app on my device, and my xPub is not imported.
I get an "Invalid Channel" error

![image](https://user-images.githubusercontent.com/55710632/102019104-43c57e00-3d26-11eb-8e15-39c9e658f64d.png)

## Environment

Using a Windows Device
Tried on both the Brave and Windows browsers
Tried using both Nano Ledger X and S

  Please fill out the following:

* Where are you running caravan:  
* Operating system: 
* Browser and version:

**Comment by JeremyNau** [comment]
I have been running a few tests and getting errors. Any thoughts on what could be driving these errors?

![image](https://user-images.githubusercontent.com/55710632/102021436-a4f44e00-3d34-11eb-9fc2-32d18b4d59c2.png)

![image](https://user-images.githubusercontent.com/55710632/102021441-ad4c8900-3d34-11eb-9f52-505ba733f17f.png)
![image](https://user-images.githubusercontent.com/55710632/102021444-b3426a00-3d34-11eb-9976-73d0ddb39cd7.png)

**Comment by JeremyNau** [comment]
Same resolution as closed #182

**Comment by waldenraines** [comment]
@JeremyNau did you set up your wallet with the words from the initial page of the test suite?  

![gscreenshot_2020-12-14-083015](https://user-images.githubusercontent.com/4116405/102086805-a9793f00-3de6-11eb-96b3-11f39a9de69e.png)

**Comment by waldenraines** [comment]
> I have been running a few tests and getting errors. Any thoughts on what could be driving these errors?

@JeremyNau did you set up your wallet with the words from the initial page of the test suite?  

![gscreenshot_2020-12-14-083015](https://user-images.githubusercontent.com/4116405/102086805-a9793f00-3de6-11eb-96b3-11f39a9de69e.png)

**Comment by waldenraines** [comment]
See also https://github.com/unchained-capital/caravan/issues/187

**Comment by JeremyNau** [comment]
No I did not. I'll have to test it and look out for that.

**Comment by waldenraines** [comment]
> No I did not. I'll have to test it and look out for that.

Yeah, the test suite tests utilize a 2/2 multisignature with one of the devices on the public words displayed in the test suite.  The other set of private keys are held by the developers.
