### ISSUE TITLE
JSON error from pasting my signature from text. is this a formatting error ?

### ISSUE THREAD

**Issue by DHB94** [unchained-capital/caravan#19]

**Comment by rsbondi** [comment]
Thank you for using caravan and reaching out.  It is most likely a formatting issue, caravan supports multiple utxos and there will be a signature for each.  It is expecting an array of values so the formatting for for a single signature:

`["304502..."]`

for multiple signatures `["304502...", "304502...", ... ]` with a comma separated quoted string for each signature.

The format attempts to be consistent with how signatures are returned from the hardware devices.

**Comment by DHB94** [comment]
Hi, thank you for your email.
I'm having trouble putting my signatures from my 3 of 6 multig Bitcoin
address in the text box, its a P2SH
type address.

**Comment by DHB94** [comment]
Not enough signatures (must be exactly one for each input).
that's the error I get when I put my signature # 1..

**Comment by rsbondi** [comment]
Can you provide more information:
How are you obtaining the signatures?
How many inputs are there in the transaction(the error message is pointing to this)?
How many unique addresses are used for inputs?
If this is testnet, maybe you could link to the address in a block explorer?

You need to sign 3 times for a 3 of 6, each time you sign you will need to sign all inputs.  So for example, if your transaction has 3 inputs you will need to paste in a valid array of 3 signatures, in the order that the corresponding public keys appear in the redeem script, into each text box for signatures that you provide using the "Enter as text" option.

**Comment by DHB94** [comment]
It’s 1 address in P2SH,
700+inputs.
could you tell me where in my data to look for my signatures please ?
Thank You, and Happy Holiday’s.
:)

**Comment by DHB94** [comment]
Could you help me to understand this please ?
 I entered my raw signed transaction in your tool from the test net issue above mine.
It’s asm doesn’t have a (all) but it also is comprised of a 0 followed by my pubkeys for my p2sh address.

**Comment by rsbondi** [comment]
In the other thread, the tx was not properly signed for multisig, for P2SH multisig you should have `0` followed by signatures, one for each of the required signatures, followed by the script, which should include the public keys.

**Comment by bucko13** [comment]
I'm going to close this issue for now as there haven't been any updates in a while. If you're still having problems and would like to post some follow up details, feel free to re-open. 

In the meantime I've filed a feature request that should help with similar circumstances in the future: #28.
