### ISSUE TITLE
Bitcoin Node - Private appears non-functional

### ISSUE THREAD

**Issue by bitcoinlizard** [unchained-capital/caravan#216]
The Private Bitcoin Client functionality appears to not work.  No matter what info is put in the URL section the response is always "Network Error".  The URL I'm pointing Caravan at can return the correct output from this command:

curl --user my_uname --data-binary \
'{"jsonrpc": "1.0", "id":"curltest", "method": "getblockcount", "params": [] }' \
-H 'content-type: text/plain;' --resolve bitcoind.localhost:8080:127.0.0.1 http://bitcoind.localhost:8080

I'm wondering if additional configuration needs to be required to give Caravan network capabilities.  I monitor the traffic from Caravan and I don't see any network traffic when I use the "Test Connection" button.

* [ ] Regression (a behavior that used to work and stopped working in a new release)
* [X] Bug report 
* [ ] Feature request
* [ ] Documentation issue or request
* [ ] Support request

## Expected Behavior

Test Connection should return successful with a proper Cors configured Bitcoin node.

## Current Behavior

Network Error is returned every time.

## Steps to Reproduce (for bugs)

Any attempt to test the connection to the Cors enabled Bitcoin node returns Network Error.  I've confirmed that my Cors configuration is working correctly with the Curl test.  

## Environment

This fails with either of these configurations:

bitcoind + configured Nginx + Caravan on the same machine
or
bitcoind + configured Nginx on one machine and Caravan access Nginx (Cors) from another machine

* Where are you running caravan:  On desktop or machine running Bitcoind and Nginx with Cors configuration
* Operating system: Linux - Ubuntu 20.04
* Browser and version: <!-- Chrome or Firefox, current versions

  If you are running caravan locally please run the following
  and paste your output below:
  
caravan: 0.3.5
npm: 6.14.4 
node: v10.19.0
Linux 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Wiingy** [comment]
Yeah same here, I can successfully curl to a remote machine on my local network running bitcoind, as per the two test's in the readme.  However, when testing connection, using the address "http://bitcoind.192.x.x.x:8080" (as per curl test) it comes up with network error.

**Comment by Wiingy** [comment]
Inspecting the page I get the following error in firefox - 
`
Loading mixed in Request (insecure) active content "http://bitcoind.192.168.1.xxx:8080/" xhr.js :177 (yellow text and box) \
Loading mixed in Request (insecure) active content "http://bitcoind.192.168.1.xxx:8080/" localhost :3000 (yellow text and box) \
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://bitcoind.192.168.1.xxx:8080/. (Reason: CORS request did not succeed). (red text and box)
`

I have also tried with self signed certificates, i can CURL using --insecure flag and IP https://bitcoind.192.168.1.xxx:8080/, when doing it firefox i only receive the Red Text CORS fault as described above

**Comment by phptek** [comment]
This appears to be a CORS issue which is documented in the `README`. You need to proxy requests to your full-node and inject the right headers there (or just use a script). See this for an nginx solution (or search for "CORS" in the README). https://github.com/unchained-capital/caravan/blob/master/bitcoind.proxy

**Comment by bitcoinlizard** [comment]
I'm going to close this ticket.  The private node functionality does work for either testnet or mainnet.  I'm currently using Caravan version 1.0.1.  Perhaps my CORS configuration was broken when I originally opened this issue but I am now able to get "Connection Success!" on testnet or mainnet and I can import my addresses on mainnet.
