### ISSUE TITLE
Enter xpub as text should allow you to enter xfp

### ISSUE THREAD

**Issue by waldenraines** [unchained-capital/caravan#219]
This means that we cannot generate the Coldcard wallet file and when you attempt to download the Coldcard config you get this error:

```
Uncaught Error: ExtendedPublicKeys missing at least one xfp.
    at coldcard.js:722
    at Array.every (<anonymous>)
    at new e (coldcard.js:719)
    at t.ConfigAdapter (index.js:526)
    at a.e.reshapeConfig (ColdcardSigner.jsx:43)
    at e.handleWalletConfigDownloadClick (ColdcardSigner.jsx:23)
    at Object.s (react-dom.production.min.js:14)
    at p (react-dom.production.min.js:14)
    at react-dom.production.min.js:14
    at v (react-dom.production.min.js:15)
```

## I'm submitting a…

* [ ] Regression (a behavior that used to work and stopped working in a new release)
* [x] Bug report 
* [x] Feature request
* [ ] Documentation issue or request
* [ ] Support request

## Expected Behavior

You should have the option of entering your fingerprint when importing your xpub via text.  Downloading Coldcard 

## Current Behavior

You do not have the option to enter the xfp when you import your xpub via text.

## Possible Solution

See above.

## Steps to Reproduce (for bugs)

1. Create a wallet using at least one Coldcard and one text xpub
2. Fund the wallet
3. Attempt to spend from the wallet
4. Click download Coldcard config
5. Note error

## Environment

* Where are you running caravan:  All
* Operating system: All
* Browser and version: All

**Comment by jevidon** [comment]
Issue migrated: https://github.com/caravan-bitcoin/caravan/issues/67

The Caravan Library is transitioning to a new home, and as part of this move current issues will be closed and archived.
