### ISSUE TITLE
Feature request: Add support for showing unsigned transaction as QR codes

### ISSUE THREAD

**Issue by starsoccer** [unchained-capital/caravan#224]
## I'm submitting a…

* [ ] Regression (a behavior that used to work and stopped working in a new release)
* [ ] Bug report 
* [X] Feature request
* [ ] Documentation issue or request
* [ ] Support request

## Expected Behavior

When showing a raw transaction there should be a QR code shown next to it, or a button to allow a QR code to be shown so it can be scanned easily.

## Current Behavior

Currently raw transactions are only show as text on screen. While this is convenient for copy and pasting it makes using with offline wallets difficult without using a QR code generator or USB device to transfer the raw transaction.

**Comment by jevidon** [comment]
The Caravan Library is transitioning to a [new home](https://github.com/caravan-bitcoin/caravan), and as part of this move all current issues will be closed and archived. This specific request will be part of a larger refactor related to QR code support we plan to execute in the future.
