### ISSUE TITLE
Hermit: "Unable to parse QR code" error when importing

### ISSUE THREAD

**Issue by demerzel3** [unchained-capital/caravan#227]
I get this error whenever I try to read a QR code generated from Hermit, both in the address generator and in wallet.
For example:

<img width="423" alt="Screen Shot 2021-07-11 at 13 13 54" src="https://user-images.githubusercontent.com/442835/125192795-e1941380-e249-11eb-97b4-8f76292ff850.png">

* [ ] Regression (a behavior that used to work and stopped working in a new release)
* [x] Bug report 
* [ ] Feature request
* [ ] Documentation issue or request
* [ ] Support request

## Expected Behavior

QR code from Hermit is read without errors.

## Current Behavior

Whenever I present a QR code I get the same "Unable to parse QR code (gzip decompression error)".

## Possible Solution

I haven't investigated the issue further so I don't know.

## Steps to Reproduce (for bugs)

1. go to https://unchained-capital.github.io/caravan/#/address
2. select "Hermit" as the first public key method
3. click "import public key"
4. present any QR code from Hermit to the webcam (or use the sample below)

<img width="598" alt="Screen Shot 2021-07-11 at 13 18 00" src="https://user-images.githubusercontent.com/442835/125192940-739c1c00-e24a-11eb-8e9b-551cf8805706.png">

## Environment

I've been able to reproduce this bug both on localhost and on the hosted version of caravan at https://unchained-capital.github.io/caravan

* Where are you running caravan:  localhost, unchained-capital.github.io
* Operating system: Mac OS
* Browser and version: Chrome Version 91.0.4472.114 (Official Build) (x86_64)

**Comment by waldenraines** [comment]
Thanks for the bug report!

What address type/network are you attempting to use?

**Comment by demerzel3** [comment]
I'm using the default settings: P2SH and Mainnet.
<img width="416" alt="Screen Shot 2021-07-22 at 15 05 11" src="https://user-images.githubusercontent.com/442835/126643774-ce8ed2e5-936b-4406-a097-21f307169b76.png">

**Comment by jevidon** [comment]
The Caravan Library is transitioning to a new home, and as part of this move current issues will be closed and archived. If you're still interested in your bug report being addressed, you're welcome to reopen it at the new location: https://github.com/caravan-bitcoin/caravan/issues
