### ISSUE TITLE
Feature Request: Support for Blockstream Jade hardware wallet

### ISSUE THREAD

**Issue by evliu** [unchained-capital/caravan#248]
The only other software I know so far that supports handling multisig with this 

## I'm submitting a…

* [ ] Regression (a behavior that used to work and stopped working in a new release)
* [ ] Bug report 
* [x] Feature request
* [ ] Documentation issue or request
* [ ] Support request

### Resources:
firmware: https://github.com/Blockstream/Jade
official software interface: https://github.com/Blockstream/green_qt
specter software: https://github.com/cryptoadvance/specter-desktop
(specter code using jade https://github.com/cryptoadvance/specter-desktop/search?q=jade)

**Comment by jevidon** [comment]
The Caravan Library is transitioning to a [new home](https://github.com/caravan-bitcoin/), and as part of this move all current issues will be closed and archived. This specific request will be part of a larger refactor related to device support we plan to execute in the future.
