### ISSUE TITLE
Feature Request: JSON parsing utilities for raw signatures and txs

### ISSUE THREAD

**Issue by bucko13** [unchained-capital/caravan#28]
Two issues related to errors with parsing pasted data: #20 and #19. It would be good to have some utilities and re-usable components for parsing these inputs and returning more descriptive errors.

**Comment by jevidon** [comment]
The Caravan Library is transitioning to a [new home](https://github.com/caravan-bitcoin/caravan), and as part of this move all current issues will be closed and archived. If you're still interested in your feature request being addressed, you're welcome to reopen it at the new location: [https://github.com/caravan-bitcoin/caravan/issues](https://github.com/caravan-bitcoin/caravan/issues)
