### ISSUE TITLE
Coinbase Vault - BIP32, BIP16

### ISSUE THREAD

**Issue by HappyCatKitten** [unchained-capital/caravan#284]
## I'm submitting a…

* [ ] Regression (a behavior that used to work and stopped working in a new release)
* [x ] Bug report 
* [ ] Feature request
* [ ] Documentation issue or request
* [ ] Support request

I have 3 XPUB keys that I would like to see the balance of, they were generated by Coinbase Vault back in 2014 however coinbase have very kindly decided to not honour upkeep of their tool which no longer works (bitpay API)

I am able to import all 3 of my XPUBS into here - https://unchained-capital.github.io/caravan/#/wallet

However the HD addresses its generating are different to the ones that the coinbase tool is generating.

BIP32, BIP16 m/0 path

I dont want to post my addresses here for security reasons, is it possible to have a secret chat?

**Comment by humanumbrella** [comment]
We are not familiar with how coinbase does their setup - make sure address type is correct.

![Screen Shot 2023-01-10 at 11 31 59 AM](https://user-images.githubusercontent.com/10471648/211644420-3950095f-1fa3-4c34-a174-43ca1ecbb9d6.png)

We default to `P2SH` but they have been using `P2WSH`
