### ISSUE TITLE
CORS instructions link incorrect

### ISSUE THREAD

**Issue by bitstein** [unchained-capital/caravan#3]
In the `ClientPicker` component, the link to CORS proxy instructions links back to the home page, rather than an instructions page.

Code: https://github.com/unchained-capital/caravan/blob/f4370f7569494cabd2f799f85c857f00453df7c5/src/components/ClientPicker.jsx#L145

![image](https://user-images.githubusercontent.com/4544062/68777688-af0ac100-05f7-11ea-8d34-33350e5bfdc4.png)

**Comment by dhruvbansal** [comment]
Thanks, just filed a PR https://github.com/unchained-capital/caravan/pull/5
