### ISSUE TITLE
Clicking "Refresh" always causes "Wallet loaded, but with errors..." and endless spinning of the Refresh icon

### ISSUE THREAD

**Issue by EmpireCreator** [unchained-capital/caravan#304]
## I'm submitting a…

* [ ] Regression (a behavior that used to work and stopped working in a new release)
* [X] Bug report 
* [ ] Feature request
* [ ] Documentation issue or request
* [ ] Support request

## Expected Behavior

After importing a mutisig wallet in Caravan ("Import Wallet Configuration") that has the address type P2WSH on mainnet, on the resulting page, the "Refresh" button under "Wallet Actions" should stop spinning after one clicks "Refresh" and display the wallet's current state without errors.

## Current Behavior

Upon importing a mutisig wallet, the "Refresh" button's icon located under "Wallet Actions" endlessly spins after "Refresh" is clicked. Additionally, every time the "Refresh" button is clicked, an error message appears, stating, "Wallet loaded, but with errors..." Despite this error message, the wallet seems to function properly, as it has successfully received and sent BTC once. (However, the presence of this error message undermines confidence and creates uncertainty.)

## Possible Solution

N/A

## Steps to Reproduce (for bugs)

1. Import wallet into Caravan
2. Observe endless spinning on "Refresh" button under "Wallet Actions"
3. Click "Refresh" button
4. Receive error message "Wallet loaded, but with errors..." and observe endless spinning of the icon that is part of the "Refresh" button

## Environment

2 of 3 multisig wallet with the address type P2WSH on mainnet. Using 3 Ledger Nano S Plus devices, newly initialized. 

* Where are you running caravan:  unchained-capital.github.io
* Operating system: macOS 13.2.1 (22D68)
* Browser and version: Chrome for Mac V. 112.0.5615.137 (Official Build) (arm64). Also Firefox 112.0.2 (64-bit). (The installation or activation of any Chrome or Firefox extensions makes no difference.)
* unchained-wallets: v.0.5.1

<img width="1552" alt="Caravan_-_Bitcoin_Multisig" src="https://user-images.githubusercontent.com/12735079/235282121-78e3b53d-28a6-4ea2-8e45-c6cb2beeee20.png">

**Comment by bucko13** [comment]
I believe this is an issue we're seeing with the public clients. Both blockstream and mempool.space have very strict rate limiting now. Mempool is working on a websocket solution that should unblock this and we'll push out an update on the [monorepo](https://github.com/caravan-bitcoin/caravan) as soon as it's ready.
