### ISSUE TITLE
After address change, BIP-32 path conflict error for existing text xpubs

### ISSUE THREAD

**Issue by mattoshibtc** [unchained-capital/caravan#305]
If you enter in a text xpub, then change the address type, there is a bip32 path conflict error that prevents you from creating a wallet. Since text xpubs don't have an associated path, this is a confusing error.

## I'm submitting a…

* [ ] Regression (a behavior that used to work and stopped working in a new release)
* [x] Bug report 
* [ ] Feature request
* [ ] Documentation issue or request
* [ ] Support request

## Expected Behavior
No BIP-32 path conflict error messages for text xpubs and successful wallet creation.

## Current Behavior
After changing the address type, there is a warning message about a BIP-32 path conflict that prevents me from creating a wallet.

## Steps to Reproduce (for bugs)

https://user-images.githubusercontent.com/129226882/236802287-0fdebd58-1962-42e8-9a16-f571206d42d1.mov

## Environment

* Where are you running caravan: unchained-capital.github.io
* Operating system: Mac
* Browser and version: Chrome

* caravan version: v0.6.0

**Comment by bucko13** [comment]
Hey @mattoshibtc thanks for filing the issue and submitting a fix! Sorry for the delay in responding. We'll be sure to take a look at this ASAP and let you know if anything needs to change before merging it in.

**Comment by jevidon** [comment]
The PR was merged, so this issue should be resolved.
