### ISSUE TITLE
Ledger test suite failures in master (0.6.0)

### ISSUE THREAD

**Issue by waldenraines** [unchained-capital/caravan#319]
## I'm submitting a…

* [ ] Regression (a behavior that used to work and stopped working in a new release)
* [x] Bug report 
* [ ] Feature request
* [ ] Documentation issue or request
* [ ] Support request

## Expected Behavior

In `0.5.0` 21 out of 23 pass.

 - Test 14 fails with:
 ```
Path too long. At most 6 levels allowed.
 ```
 - Test 16 fails with:
 ```
Ledger device: Invalid data received (0x6a80)
 ```

![image](https://github.com/unchained-capital/caravan/assets/4116405/4af81a62-48ef-47dc-8fa9-654ca1d6bbaf)

## Current Behavior

In `0.6.0` 18 out of 32 pass.

 - Test 14 fails with:
 ```
Path too long. At most 6 levels allowed.
 ```
 - Tests 15, 16, 17, 18, 21, 22, 23, and 24 fail with:
```
Ledger device: UNKNOWN_ERROR (0xb008)
```

 - Test 19 fails with:
 ```
Ledger device: Invalid data received (0x6a80)
 ```

 - Tests 27, 28, 29, and 30 fail with variations of the diff being off, for example:
 ```
Expected:
6fb498be86e7accd2b264c6d129e2b1bf5edad95dbc194db962ca8958c4af0c9
Actual:
fb633e6a50ff05a1a090e07f2586d11f04b4ee8052cd0ce9ed816f8c4446cdc3
Diff:
6fb498b633e86a50ff05a1a090e07accdf2b25864c6d129e2b1f04bf54edad9e8052cdb0c1e94edb98162caf8958c4af0446c9dc3
 ```  

![image](https://github.com/unchained-capital/caravan/assets/4116405/96f3eb34-5302-4f1e-9334-04f7730557f6)

Note that normal usage of Ledger within caravan seems to work fine.  This problem is only in the test suite.

## Possible Solution

Fix the tests.

## Steps to Reproduce (for bugs)

1. Run the test suite in 0.6.0 with a ledger

## Environment

* Where are you running caravan:  localhost
* Operating system: Linux
* Browser and version: All

```
> npm ls caravan unchained-bitcoin unchained-wallets; echo -e npm: `npm -v` \\nnode: `node -v`;  uname -a | xargs echo | cut -d " " -f 1,3-15 || sw_vers
caravan@0.6.0 /home/walden/code/caravan
├── unchained-bitcoin@0.4.1
└─┬ unchained-wallets@0.5.1
  └── unchained-bitcoin@0.4.1 deduped

npm: `npm -v`
node: `node -v`
Linux 6.0.6-76060006-generic #202210290932~1667401208~22.04~d2df702 SMP PREEMPT_DYNAMIC Wed N x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jevidon** [comment]
Issue migrated: https://github.com/caravan-bitcoin/caravan/issues/66

The Caravan Library is transitioning to a new home, and as part of this move current issues will be closed and archived.
