### ISSUE TITLE
Caravan does not recognize Ledger policyHmacs from imported Unchained wallet config files

### ISSUE THREAD

**Issue by typercampbell** [unchained-capital/caravan#335]
## I'm submitting a 

* [ ] Regression (a behavior that used to work and stopped working in a new release)
* [x] Bug report 
* [ ] Feature request
* [ ] Documentation issue or request
* [ ] Support request

## Expected Behavior

When I load up my wallet configuration file, I expect any ledgerPolicyHmacs in my wallet config file to be brought over and fully imported into Caravan as well.,

## Current Behavior

Currently, in order to successfully sign with my Ledger in Caravan, I must re-register the device as the ledgerPolicyHmac for my multisig wallet does not carry over. If I don't re-register, I receive `Ledger device: UNKNOWN_ERROR (0xb008)`

## Possible Solution

I am unsure about the solution, but I feel it's worth calling out. 

## Steps to Reproduce (for bugs)

1. Register a Ledger with an Unchained vault
2. Download the config file, and examine it to ensure the policyHac is in the file
3. Import the file into Caravan and proceed without registering Ledger again
4. Attempt to sign and receive `Ledger device: UNKNOWN_ERROR (0xb008)`

## Environment

* Where are you running caravan:  unchained-capital.github.io
* Operating system: Mac
* Browser and version: Chrome

**Comment by jevidon** [comment]
Ordering and naming were previously an issue but should be resolved now.
