### ISSUE TITLE
TypeError: Cannot destructure property 'bip32Path' of 'this.state' as it is undefined.

### ISSUE THREAD

**Issue by javiervargas** [unchained-capital/caravan#338]
## I'm submitting a…

* [ ] Regression (a behavior that used to work and stopped working in a new release)
* [x] Bug report 
* [ ] Feature request
* [ ] Documentation issue or request
* [ ] Support request

## Expected Behavior
 It should load pub key from Ledger.

## Current Behavior
It show a message : Expected hex value of length 8 in red.

Attach javascript log:

`TypeError: Cannot destructure property 'bip32Path' of 'this.state' as it is undefined.

    at Fue (https://mydomain.com/caravan/assets/index-0ae184a5.js:907:7201)
    at div
    at div
    at https://mydomain.com/caravan/assets/index-0ae184a5.js:79:24621
    at https://mydomain.com/caravan/assets/index-0ae184a5.js:189:85156
    at div
    at https://mydomain.com/caravan/assets/index-0ae184a5.js:79:24621
    at https://mydomain.com/caravan/assets/index-0ae184a5.js:116:26845
    at https://mydomain.com/caravan/assets/index-0ae184a5.js:79:24621
    at https://mydomain.com/caravan/assets/index-0ae184a5.js:189:82532
    at TGe (https://mydomain.com/caravan/assets/index-0ae184a5.js:907:10006)
    at L (https://mydomain.com/caravan/assets/index-0ae184a5.js:55:3692)`

## Steps to Reproduce (for bugs)
Attach screen
<img width="1433" alt="Screenshot 2023-08-29 at 22 24 41" src="https://github.com/unchained-capital/caravan/assets/7927115/3590c7f4-2b1b-46f0-a629-738ce4277d9d">

1. Upload pub key from first HW.
2. Select ledger
3. Legder is connected and unlocked
4. Click button

## Environment

 Testnet

* Where are you running caravan:  Own machine 
* Operating system: uname -a Linux # 9~22.04.3-Ubuntu SMP Tue Aug  1 21:11:51 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

* Browser and version: MacOS - Chrome Version 113.0.5672.126 (Official Build) (arm64) 

 npm: 9.8.1 
node: v16.20.2
Linux 6.2.0-1009 # 9~22.04.3-Ubuntu SMP Tue Aug 1 21:11:51 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by fmalykh** [comment]
hi,
is this fixed? getting the same error running `v0.7.0 commit: 6139b9b`

**Comment by javiervargas** [comment]
This is related to software versions or Cache.
