### ISSUE TITLE
Error Loading Wallet from JSON Configuration Files in Caravan Multisig

### ISSUE THREAD

**Issue by EmpireCreator** [unchained-capital/caravan#364]
## I'm submitting a…

* [ ] Regression (a behavior that used to work and stopped working in a new release)
* [X] Bug report 
* [ ] Feature request
* [ ] Documentation issue or request
* [ ] Support request

## Expected Behavior

I expected that after selecting and uploading a JSON wallet configuration file previously downloaded from Caravan Multisig, the wallet would load without any errors.

## Current Behavior

The configuration file appears to upload correctly. The Extended Public Keys, Name, and Key Origin values from the JSON file load correctly. The message "You have imported all 3 extended public keys" is displayed, followed by a prompt to confirm the information. After pressing "Confirm," the wallet seems to load, but only partially. The balance starts to appear, and the loading spinner is active, but after a few seconds (about 20% into the loading process), the error message 'Wallet loaded, but with errors...' is displayed.

## Possible Solution

A possible solution could be reverting back to a previous version of the code where this issue was not present. I have been using Caravan Multisig for over a year with several JSON files for different 2 of 3 multisig wallets and have not encountered this problem until the last 24 hours.

## Steps to Reproduce (for bugs)

Step 1: From the main screen, click "Import Wallet Configuration."

Step 2: Select a JSON file from one of several 2 of 3 wallet configuration files.

Step 3: Press "Confirm" after the details from the JSON file appear on screen for confirmation.

Step 4: On the next screen, observe the spinner spinning and the partial appearance of the wallet balance.

Step 5: Notice the progress indicator stalls and takes much longer than usual, timing out after about 1/5th of the progress.

Step 6: Encounter the error message "Wallet loaded, but with errors..." or experience a perpetual hanging of the progress indicator without an error message.

## Environment

- Where are you running Caravan: unchained-capital.github.io
- Operating System: MacOS on MacBook Pro (late 2021 model, using latest MacOS 14.1.2 (23B92)
- Browser and Version: Chrome 120.0.6099.216 and Safari Version 17.1.2 (19616.2.9.11.12)
- caravan version: v1.0.1 commit: 7fcc139

**Comment by bucko13** [comment]
Thanks for logging this issue!

We believe this is being caused by recent rate limiting added to mempool.space which we just migrated to use for the public wallet backend. 

They have a library published for using with wallet backends: https://github.com/mempool/mwck-js

I'm going to try and publish a patch that uses this instead of the normal REST api. If this ends up being a more involved fix, then we'll rollback to use blockstream.info while we work on a more comprehensive fix.

**Comment by bucko13** [comment]
Ah, heh. Already answered this. Going to close. Hopefully mempool's websocket client is ready soon.
