### ISSUE TITLE
 upgrade trezor-connect dependency to latest

### ISSUE THREAD

**Issue by prusnak** [unchained-capital/caravan#43]
Please upgrade the trezor-connect[1] dependency of your application to
latest (8.1.1 atm), otherwise your users won't be able to enter the
passphrase on the device.

Thanks!

[1] https://www.npmjs.com/package/trezor-connect

**Comment by bucko13** [comment]
Thanks! We plan on doing a thorough round of testing over the coming week.

**Comment by bucko13** [comment]
Latest release of Caravan includes updates to the trezor-connect dependency. Thanks for the heads up!
