### ISSUE TITLE
Spend specific UTXO rather than all at once

### ISSUE THREAD

**Issue by sahilc0** [unchained-capital/caravan#54]
## I'm submitting a…

* [ ] Regression (a behavior that used to work and stopped working in a new release)
* [ ] Bug report 
* [x] Feature request
* [ ] Documentation issue or request
* [ ] Support request

## Expected Behavior
If user has UTXOs with 0.1, 0.7, 0.4, 0.5 BTC each - user should be able to spend 0.1 UTXO without having to spend others back as "change" to self-address

## Current Behavior
Unless I'm misunderstanding, currently Caravan requires spending all UTXOs in one txn.

**Comment by waldenraines** [comment]
> If user has UTXOs with 0.1, 0.7, 0.4, 0.5 BTC each - user should be able to spend 0.1 UTXO without having to spend others back as "change" to self-address

Stay tuned :slightly_smiling_face:. 

If you're interested in this functionality you can take a look at the branch `wallet-dev`.  But please note that this branch is very much in active development and should currently only be used with testnet coins.

**Comment by bucko13** [comment]
In the latest release this is _partially_ resolved. There still isn't support for full utxo selection, however you can select them on a per address basis when using the wallet view. This is definitely a high priority feature that we would definitely like to support very soon.
