### ISSUE TITLE
Feature Request: Complex multi-sig

### ISSUE THREAD

**Issue by fresheneesz** [unchained-capital/caravan#6]
I'd like to be able to create a wallet where the funds with eg keys A, B, C, and D, where:

1. Funds can be spent using *only* key A
2. Funds can be spent using 2/3 out of B, C, and D. 

To do this, I propose extending the Quorum UI element so you can add additional N-of-M options. So you would have something that says:

```
+    +
2 of 3
-      -
Add Condition
```

And when "Add Condition" is clicked, it shows another line:

```
+    +
2 of 3
-      -
+    +
2 of 3
-      -
Add Condition
```

There would then have to be a corresponding way to decide which public key on the left went to which quorum on the right.

**Comment by dhruvbansal** [comment]
See also https://gist.github.com/nothingmuch/62a504414ccc37ed195741738b089a8f for another use case of complex scripts.

**Comment by destrys** [comment]
This is a great request, but I don't think any hardware wallet can sign a multi-multi-sig =)
It's unlikely any hardware wallet will support this before taproot/mast is merged.

**Comment by jevidon** [comment]
The Caravan Library is transitioning to a [new home](https://github.com/caravan-bitcoin/caravan), and as part of this move all current issues will be closed and archived. If you're still interested in your feature request being addressed, you're welcome to reopen it at the new location: [https://github.com/caravan-bitcoin/caravan/issues](https://github.com/caravan-bitcoin/caravan/issues)
