### ISSUE TITLE
Refactor Request: zero-index transaction outputs

### ISSUE THREAD

**Issue by destrys** [unchained-capital/caravan#93]
## I'm submitting a…

* [ ] Regression (a behavior that used to work and stopped working in a new release)
* [ ] Bug report 
* [x] Feature request
* [ ] Documentation issue or request
* [ ] Support request

## Current Behavior

Transaction outputs are currently one-indexed. 
For an example, see `deleteOutput` in`transactionReducer.js`.
This is ripe for a bug.

## Possible Solution

Transaction Inputs and Outputs should be zero-indexed everywhere.

**Comment by jevidon** [comment]
The Caravan Library is transitioning to a [new home](https://github.com/caravan-bitcoin/caravan), and as part of this move all current issues will be closed and archived. If you're still interested in your request being addressed, you're welcome to reopen it at the new location: [https://github.com/caravan-bitcoin/caravan/issues](https://github.com/caravan-bitcoin/caravan/issues)
